// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDovzS6xb4bgO4tOVSntNKYCCSR50Bj8V0',
    appId: '1:396094504184:web:89c3a5f2d3f88f6e3c4f0d',
    messagingSenderId: '396094504184',
    projectId: 'notes-keep-flutter-app',
    authDomain: 'notes-keep-flutter-app.firebaseapp.com',
    storageBucket: 'notes-keep-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGY_Hejzct9PNkTwBOxywKhB05dWJMHZE',
    appId: '1:396094504184:android:73c7cf2a2258de173c4f0d',
    messagingSenderId: '396094504184',
    projectId: 'notes-keep-flutter-app',
    storageBucket: 'notes-keep-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTpb8eZ0WJwB1mMgiFR19f2b6UgBm154o',
    appId: '1:396094504184:ios:ce1ad95d4ad6bfcb3c4f0d',
    messagingSenderId: '396094504184',
    projectId: 'notes-keep-flutter-app',
    storageBucket: 'notes-keep-flutter-app.appspot.com',
    iosBundleId: 'com.ultrapronoob.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTpb8eZ0WJwB1mMgiFR19f2b6UgBm154o',
    appId: '1:396094504184:ios:2fac17b727e465a03c4f0d',
    messagingSenderId: '396094504184',
    projectId: 'notes-keep-flutter-app',
    storageBucket: 'notes-keep-flutter-app.appspot.com',
    iosBundleId: 'com.ultrapronoob.mynotes.RunnerTests',
  );
}
